int x = 3;
Console.WriteLine("Wzór -> -x^3 + 2x^2 - ax - 4 ");
Console.WriteLine($"Wynik: {(-x*x*x)+ (2*x*x)-4}-{x}a\n");
Console.WriteLine("Wzór -> 9x^4 - 12x^2 + 4");
Console.WriteLine($"Wynik: {(9*x*x*x*x)-(12*x*x)+4}\n");
Console.WriteLine("Wzór -> 9x^4 + 12x^2 + 4");
Console.WriteLine($"Wynik: {(9*x*x*x*x)+(12*x*x)+4}\n");
Console.WriteLine("Wzór -> 9x^4 - 4");
Console.WriteLine($"Wynik: {(9*x*x*x*x)-4}\n");
Console.WriteLine("Wzór -> 9x^4 + 4");
Console.WriteLine($"Wynik: {(9*x*x*x*x)+4}\n");
Console.WriteLine("Wzór -> x^2 - 4x + 4");
Console.WriteLine($"Wynik: {(x*x)-(4*x)+4}\n");
Console.WriteLine("Wzór -> x^2 + 2x + 4");
Console.WriteLine($"Wynik: {(x*x) + (2*x) + 4}\n");
Console.WriteLine("Wzór -> (1-x)(x+2)(x^2-4)");
Console.WriteLine($"Wynik: {(1-x)*(x+2)*((x*x)-4)}\n");
Console.WriteLine("Wzór -> (x-3)(x+3)(x^2-9)");
Console.WriteLine($"Wynik: {(x-3)*(x+3)*((x*x)-9)}\n");
Console.WriteLine("Wzór -> (x^2+1)(x^2+4)(x^2+3)");
Console.WriteLine($"Wynik: {((x*x)+1)*((x*x)+4)*((x*x)+3)}\n");
Console.WriteLine("Wzór -> (2-x)(x+3)(x^2-1)");
Console.WriteLine($"Wynik: {(2-x)*(x+3)*((x*x)-1)}\n");
Console.WriteLine("Wzór -> x^3 - 3x^2 + 5x - 15");
Console.WriteLine($"Wynik: {(x*x*x)-(3*(x*x))+(5*x)-15}\n");
Console.WriteLine("Wzór -> 2x^3 - x^2 - 6x + 3");
Console.WriteLine($"Wynik: {(2*(x*x*x))-(x*x)-(6*x)+3}\n");
